init
YaroslavGlonin/Chargerapp pull request #1
Opened 2023-05-15 20:17 UTC by YaroslavGlonin

2023-05-15 20:22 UTC, YaroslavGlonin commented
![1](https://github.com/YaroslavGlonin/Chargerapp/assets/10401959/a4bd192c-463e-41c1-a2d8-61d07929581d)

2023-05-16 06:21 UTC, pvd-teacher requested changes

2023-05-16 06:21 UTC, pvd-teacher commented on app/src/main/java/com/kiparo/chargerapp/di/DataModule.kt
> +    single <OpenChangeMapRepository>{ OpenChangeMapRepositoryImpl(retrofit = get())  }
single нужен только если храним состояние в репозитории, но мы не должны там хранить состояние, поэтому должен быть factory

2023-05-16 06:21 UTC, pvd-teacher commented on app/src/main/java/com/kiparo/chargerapp/ui/MainActivity.kt
> +        startFragment()
попробуйте инициировать пересоздание экрана, сколько у вас будет фрагментов?

2023-05-16 06:21 UTC, pvd-teacher commented on app/src/main/java/com/kiparo/chargerapp/ui/MainActivity.kt
> +    private fun startFragment(){
а если все таки сделать через интерфейс 
например 
```
interface Navigator{
   openMap()
}
```

2023-05-16 12:28 UTC, YaroslavGlonin commented on app/src/main/java/com/kiparo/chargerapp/ui/MainActivity.kt
> +    private fun startFragment(){
Не совсем понял, как вынести создание фрагмента, можно пример

2023-05-21 13:09 UTC, tim-teacher requested changes

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/api/ApiRetrofit.kt
> +
А зачем вам два API?

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/constant/Constant.kt
> +}
Константы за пределы `object` вынести, а `CAMERA_TARGET` создавать там где это нужно, координаты тоже в константы вынести

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/data/AddressInfo.kt
> +    val AddressLine1: String,
Конвеншены

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/data/Connection.kt
> +    val Amps: Int,
Конвеншены

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/data/OpenChargeMapData.kt
> +    val AddressInfo: AddressInfo,
Конвеншены. А зачем вам все данные? Можно забирать только те которые вам нужны

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/data/interceptors/ErrorInterceptor.kt
> +                404 -> NotFoundException()// Not Found
`NotFoundException` на `AppException` заменить или другой свой

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/di/DataModule.kt
> +    single <OpenChangeMapRepository>{ OpenChangeMapRepositoryImpl(retrofit = get())  }
Не исправлено

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/repository/OpenChangeMapRepository.kt
> +                           compact:Boolean,
1) Зачем key передавать из UI?
2) Все параметры занести в модель и передавать сюда модель а не миллион аргументов
3) Вам нужны только координаты квадрата, зачем вам дистанция, compact(можно в интерфейсе только указать), verbose (тоже самое), distanceunit.

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/repository/OpenChangeMapRepository.kt
> +                                      verbose:Boolean): List<OpenChargeMapData>
Тоже самое, непонятно зачем 2 метода

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/ui/MainActivity.kt
> +        startFragment()
Да, только у вас этого нет. Не исправлено

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/ui/MainActivity.kt
> +    private fun startFragment(){
Павел имел ввижу просто создать интерфейс и реализовать его тут в активити, что бы startFragment был методом интерфейса

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/ui/MapFragment.kt
> +    inner class TextImageProvider(private val text: String) : ImageProvider() {
Вынести в отдельный файл

2023-05-21 13:09 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/ui/MapFragment.kt
> +        private const val STROKE_SIZE = 3f
В константы вынести за пределами `companion object` и класса

2023-05-25 22:12 UTC, tim-teacher commented
Хорошо бы еще добавить что бы при клике на кластер мы приближались к нему.

Не обязательно это делать, заметил просто в приложении.

2023-05-25 22:12 UTC, tim-teacher requested changes

2023-05-25 22:12 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/data/interceptors/ErrorInterceptor.kt
> +                404 -> NotFoundException()// Not Found
?

2023-05-25 22:12 UTC, tim-teacher commented on app/src/main/java/com/kiparo/chargerapp/di/DataModule.kt
> +    single <OpenChangeMapRepository>{ OpenChangeMapRepositoryImpl(retrofit = get())  }
?

2023-05-25 22:13 UTC, tim-teacher approved these changes
Поставил апрув, но ошибок еще хватает. Вливайте код в следующее ДЗ и там уже будем смотреть.

2023-05-26 17:55 UTC, merged